---
- name: Create Vagrant VMS
  community.vagrant.vagrant:
    instances: "{{ vms }}"
    default_box: "{{ vagrant_box }}"
    provider_name: "{{ vagrant_provider }}"
    state: up
    workdir: "{{ role_path }}"
