---
- name: Deploy Vagrant VMs
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/vagrant.yml

  tasks:
    - name: Create Vagrant VMs
      community.vagrant.vagrant:
        instances: "{{ vms }}"
        default_box: "{{ vagrant_box }}"
        provider_name: "{{ vagrant_provider }}"
        state: up
        workdir: "{{ playbook_dir }}"
